import { query, withTransaction } from '../db';
import { AppError } from '../middleware/errorHandler';

export class TicketService {
  /** Create a ticket (manual or auto-generated) */
  static async create(data: {
    title: string;
    description?: string;
    category?: string;
    priority?: string;
    createdByUserId?: string;
    linkedTransactionId?: string;
    isAutoGenerated?: boolean;
  }) {
    const validCategories = ['general','payment_hold','maintenance','billing','access','other','kyc_verification','account_suspended','technical'];
    let cat = (data.category || 'general').toLowerCase();
    if (!validCategories.includes(cat)) cat = 'general';

    const validPriorities = ['low','medium','high','urgent'];
    let prio = (data.priority || 'medium').toLowerCase();
    if (!validPriorities.includes(prio)) prio = 'medium';

    const res = await query(
      `INSERT INTO tickets
         (title, description, category, priority, created_by, linked_transaction_id, is_auto_generated)
       VALUES ($1, $2, $3, $4, $5, $6, $7)
       RETURNING *`,
      [
        data.title,
        data.description || null,
        cat,
        prio,
        data.createdByUserId || null,
        data.linkedTransactionId || null,
        data.isAutoGenerated || false,
      ]
    );
    return res.rows[0];
  }

  /** List tickets (role-scoped) */
  static async list(
    userId: string,
    roles: string[],
    filters: { status?: string; category?: string; page?: number; limit?: number }
  ) {
    const page = filters.page || 1;
    const limit = filters.limit || 20;
    const offset = (page - 1) * limit;

    let whereClause = 'WHERE 1=1';
    const params: any[] = [];
    let paramIdx = 1;

    // Role scoping: staff see only their assigned tickets; vendors/tenants see their own
    if (roles.includes('super_admin') || roles.includes('admin')) {
      // Full access – no extra filter
    } else if (roles.includes('staff')) {
      whereClause += ` AND t.assigned_staff_id = $${paramIdx++}`;
      params.push(userId);
    } else {
      whereClause += ` AND t.created_by = $${paramIdx++}`;
      params.push(userId);
    }

    if (filters.status) {
      whereClause += ` AND t.status = $${paramIdx++}`;
      params.push(filters.status);
    }
    if (filters.category) {
      whereClause += ` AND t.category = $${paramIdx++}`;
      params.push(filters.category);
    }

    params.push(limit, offset);

    const res = await query(
      `SELECT
         t.*,
         creator.display_name AS created_by_name,
         creator.email        AS created_by_email,
         staff.display_name   AS assigned_staff_name,
         txn.amount           AS linked_txn_amount,
         txn.hold_status      AS linked_txn_hold_status
       FROM tickets t
       LEFT JOIN users creator ON creator.id = t.created_by
       LEFT JOIN users staff   ON staff.id = t.assigned_staff_id
       LEFT JOIN transactions txn ON txn.id = t.linked_transaction_id
       ${whereClause}
       ORDER BY
         CASE t.priority WHEN 'urgent' THEN 1 WHEN 'high' THEN 2 WHEN 'medium' THEN 3 ELSE 4 END,
         t.updated_at DESC
       LIMIT $${paramIdx++} OFFSET $${paramIdx++}`,
      params
    );

    const countRes = await query(
      `SELECT COUNT(*) FROM tickets t ${whereClause}`,
      params.slice(0, params.length - 2)
    );

    return {
      data: res.rows,
      meta: { total: parseInt(countRes.rows[0].count, 10), page, limit },
    };
  }

  /** Get one ticket with comments */
  static async getById(ticketId: string) {
    const ticketRes = await query(
      `SELECT
         t.*,
         creator.display_name AS created_by_name,
         creator.email        AS created_by_email,
         staff.display_name   AS assigned_staff_name,
         txn.amount           AS linked_txn_amount,
         txn.hold_status      AS linked_txn_hold_status,
         txn.hold_release_date AS linked_txn_release_date,
         txn.net_amount       AS linked_txn_net_amount,
         txn.platform_fee_amount AS linked_txn_fee_amount
       FROM tickets t
       LEFT JOIN users creator ON creator.id = t.created_by
       LEFT JOIN users staff   ON staff.id = t.assigned_staff_id
       LEFT JOIN transactions txn ON txn.id = t.linked_transaction_id
       WHERE t.id = $1`,
      [ticketId]
    );
    if (ticketRes.rows.length === 0) throw new AppError('Ticket not found', 404);

    const commentsRes = await query(
      `SELECT tc.*, u.display_name AS sender_name, u.avatar_url AS sender_avatar
       FROM ticket_comments tc
       LEFT JOIN users u ON u.id = tc.sender_id
       WHERE tc.ticket_id = $1
       ORDER BY tc.created_at ASC`,
      [ticketId]
    );

    return { ...ticketRes.rows[0], comments: commentsRes.rows };
  }

  /** Assign a ticket to a staff member */
  static async assign(ticketId: string, staffId: string) {
    // Verify the target is actually staff
    const staffCheck = await query(
      `SELECT id FROM user_roles WHERE user_id = $1 AND role = 'staff'`,
      [staffId]
    );
    if (staffCheck.rows.length === 0)
      throw new AppError('Target user is not a staff member', 400);

    const res = await query(
      `UPDATE tickets
       SET assigned_staff_id = $1, status = 'in_progress', updated_at = NOW()
       WHERE id = $2
       RETURNING *`,
      [staffId, ticketId]
    );
    if (res.rows.length === 0) throw new AppError('Ticket not found', 404);
    return res.rows[0];
  }

  /** Update ticket status */
  static async updateStatus(ticketId: string, status: string, resolutionNotes?: string) {
    const validStatuses = ['open','in_progress','pending_response','resolved','closed','cancelled'];
    if (!validStatuses.includes(status))
      throw new AppError('Invalid status', 400);

    const res = await query(
      `UPDATE tickets
       SET status = $1::varchar,
           resolution_notes = COALESCE($2, resolution_notes),
           resolved_at = CASE WHEN $1::varchar IN ('resolved','closed') THEN NOW() ELSE resolved_at END,
           updated_at = NOW()
       WHERE id = $3
       RETURNING *`,
      [status, resolutionNotes || null, ticketId]
    );
    if (res.rows.length === 0) throw new AppError('Ticket not found', 404);
    return res.rows[0];
  }

  /** Post a comment on a ticket */
  static async addComment(data: {
    ticketId: string;
    senderId: string;
    senderRole: string;
    message: string;
    isInternal?: boolean;
  }) {
    const res = await query(
      `INSERT INTO ticket_comments (ticket_id, sender_id, sender_role, message, is_internal)
       VALUES ($1, $2, $3, $4, $5)
       RETURNING *`,
      [
        data.ticketId,
        data.senderId,
        data.senderRole,
        data.message,
        data.isInternal || false,
      ]
    );

    // Update ticket updated_at so it surfaces in sorted lists
    await query(
      `UPDATE tickets SET updated_at = NOW() WHERE id = $1`,
      [data.ticketId]
    );

    return res.rows[0];
  }

  /** Get ticket statistics for admin */
  static async getStats() {
    const res = await query(`
      SELECT
        COUNT(*) FILTER (WHERE status = 'open')                    AS open_count,
        COUNT(*) FILTER (WHERE status = 'in_progress')             AS in_progress_count,
        COUNT(*) FILTER (WHERE status = 'pending_response')        AS pending_count,
        COUNT(*) FILTER (WHERE status IN ('resolved','closed'))    AS resolved_count,
        COUNT(*) FILTER (WHERE category = 'payment_hold')          AS payment_hold_count,
        COUNT(*) FILTER (WHERE is_auto_generated = true)           AS auto_generated_count,
        COUNT(*) FILTER (WHERE assigned_staff_id IS NULL AND status = 'open') AS unassigned_open
      FROM tickets
    `);
    return res.rows[0];
  }
}
